### ISSUE TITLE
It seems a target action is updated only if it is deployed twice.

### ISSUE THREAD

**Issue by style95** [naver/openwhisk-intellij-plugin#5]
Also, the file view with a virtual file needs to be refreshed with the latest codes.

**Comment by KeonHee** [comment]
It is an issue that the changed code or manifest.yaml file is not applied when the wskdeploy deploy command is executed without saving(ctl+s).

**Comment by style95** [comment]
It was because the file was not saved at the IDE layer.
So closing.
